### ISSUE TITLE
Not Advertising

### ISSUE THREAD

**Issue by markrennie71** [Roemer/ut99-server#1]
Hello, i see this used a bridged network not host. I can connect to the server via ip address but not see it in the LAN server lists. I have checked advertise server, restart etc but still no joy. Any idea please? is it s port?

Cheers
Mark

**Comment by Roemer** [comment]
I have no idea why that is. But if you find something I will gladly add this. I now added an option to advertise the server on the official server list but I need to verify that it works.

**Comment by RIKIKU** [comment]
Looks like it is a port. If you add 8777:8777/udp  to the list of ports in your docker run command, it should show up on the LAN.  

It looks like the UT client sends a broadcast packets out to each UDP port within this range 8777-8786 and it just scans through them constantly. 
I noticed that you can run (on windows) multiple UT servers at the same time and when you do, the server automatically assigns the next port in the range to the server.

so, when you open one instance of the UT server the following ports start listening:
7777
7778
8777

when you open a second instance of the server at the same time, the following ports are listening:
7777
7777
7778
7779
8777
8778

**Comment by Roemer** [comment]
I think this is fixed now with the port 8777?

**Comment by Roemer** [comment]
Did anyone ever get LAN advertising to work?

**Comment by RIKIKU** [comment]
Yes, mapping Port 8777 fixes it.

**Comment by Roemer** [comment]
Strange, it does not work for me, at least with the GOTY Edition from Steam.

**Comment by Roemer** [comment]
Hmm when I check the Log (Tools->Show Log) in UT Client it shows: `Init: WinSock: I am <pc> (172.31.128.1)` which is the IPv4 of one of my vEthernet Adapters and not my real LAN ip. Maybe that is the cause? anybody knows if/how this could be fixed?

**Comment by RIKIKU** [comment]
This is my docker-compose file and it is definitely working for me.

```
version: "3.2"
services:
  ut99:
    image: roemer/ut99-server:latest
    container_name: ut99
    volumes:
            - ut99-data:/ut-data
    environment:
      - UT_SERVERNAME=Testing UT Server In Docker
      - UT_WEBADMINUSER=redacted
      - UT_WEBADMINPWD=redacted
      - UT_DOUPLINK=True
      - UT_SERVERURL=CTF-Face?game=BotPack.CTFGame?mutator=BotPack.InstaGibDM,MapVoteLAv2.BDBMapVote,FlagAnnouncementsV2.FlagAnnouncements

    ports:
      #Webadmin
      - 5580:5580
      #Game Play
      - 7777:7777/udp
      #Game Query
      - 7778:7778/udp
      #beacon port
      - 7779:7779/udp
      #LAN Discovery
      - 8777:8777/udp
    restart: always
volumes:
   ut99-data:
```

My client version is: 469.  

I can see it advertise on the LAN and I can connect and play on that server.
